# Generated by Django 2.1.2 on 2018-12-15 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LED',
            new_name='Device',
        ),
    ]
